config:
  inCluster: false

volumeMounts:
  - name: kubeconfig
    mountPath: /home/headlamp/.config/Headlamp/kubeconfigs

volumes:
  - name: kubeconfig
    secret:
      secretName: headlamp-kubeconfig
